version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=127.0.0.1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      -.:/app
    command: npm run start
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD: root_password
      - MYSQL_DATABASE: ${DB_NAME}
      - MYSQL_USER: ${DB_USER}
      - MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:var/lib/mysql

volumes:
  mysql_data: